controllers/auth_controller.py
from flask import Flask, render_template, request, redirect, url_for, flash, Blueprint
from database.config import Session
from models.models import Nutricionista,  Paciente
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import check_password_hash

auth_bp = Blueprint('auth', __name__, url_prefix='/auth', template_folder='templates')
session = Session()

login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    user = session.query(Nutricionista).get(int(user_id)) 
    if user is None:
        user = session.query(Paciente).get(int(user_id))
    return user

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        senha = request.form['senha']
        nutricionista = session.query(Nutricionista).filter_by(nutri_email=email).first()

        erros = {}

        if not nutricionista:
            erros['email'] = 'E-mail não encontrado.'
        elif not nutricionista.check_password(senha):
            erros['senha'] = 'Senha incorreta.'

        if erros:
            return render_template('auth/login.html', erros=erros, form=request.form)


        if nutricionista and nutricionista.check_password(senha):
            login_user(nutricionista)
            flash('Login realizado com sucesso!')
            return redirect(url_for('nutricionista.dashboard'))
        else:
            flash('Email ou senha incorretos.')

    return render_template('auth/login.html', erros={}, form={})

@auth_bp.route("/cadastro", methods=['GET', 'POST'])
def cadastro():
    if request.method == 'POST':
        nome = request.form['nome']
        email = request.form['email']
        senha = request.form['senha']
        cpf = request.form['cpf']
        crn = request.form['crn']
        telefone = request.form['telefone']
        erros = {}

        if session.query(Nutricionista).filter_by(nutri_email=email).first():
            erros['email'] = 'E-mail já cadastrado.'
        if session.query(Nutricionista).filter_by(nutri_cpf=cpf).first():
            erros['cpf'] = 'CPF já cadastrado.'
        if session.query(Nutricionista).filter_by(nutri_crn=crn).first():
            erros['crn'] = 'CRN já cadastrado.'
        if session.query(Nutricionista).filter_by(nutri_telefone=telefone).first():
            erros['telefone'] = 'Telefone já cadastrado.'

        if erros:
            return render_template("auth/cadastro.html", erros=erros, form=request.form)

        novo_nutricionista = Nutricionista(nutri_nome=nome,nutri_email=email,nutri_cpf=cpf,nutri_telefone=telefone,nutri_senha=senha, nutri_crn=crn)
        novo_nutricionista.set_password(senha)
        session.add(novo_nutricionista)
        session.commit()
        login_user(novo_nutricionista)
        return redirect(url_for('auth.login'))

    return render_template("auth/cadastro.html", erros={}, form={})

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Você foi desconectado.')
    return redirect(url_for('index'))

templates/funcionalidades.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SmartNutri</title>
        <link rel="stylesheet" type="text/css" href="/static/css/funcionalidades.css">
    </head>
    <body>
        <header>
            <nav>
                <a href = "{{ url_for('index')}}">
                  <img src="static/img/smartnutri.png" alt="logo">
                </a>
                <ul>
                    <li><a href="{{ url_for('consulta')}}">Consulta</a></li>
                    <li><a href="{{ url_for('dieta')}}" id="contato">Dieta</a></li>
                </ul>
                <a href="{{ url_for('login')}}" class="button">Entrar</a>
            </nav>
        </header>

        <main class="main">
            <h1>Crie um plano alimentar exclusivo para o seu cliente e tanana</h1>
            <div class="image-container">
            <img src="static/img/plano-alimentar.jpg" alt="Alimentos e plano alimentar">
            </div>
            <div class="div2">
                <div class="gallery">
                <img src="static/img/plano-alimentar.jpg" alt="Imagem 1">
                <img src="static/img/balanca.jpeg" alt="Imagem 2">
                <img src="static/img/comida.jpeg" alt="Imagem 3">
                </div>
                <button class="btn-experimente"><a href="/cadastro.html">EXPERIMENTE</a></button>
            </div>
        </main>


        <section class="registro-alimentos">
            <div class="conteudo-secao">
              <div class="imagem-registro">
                <img src="static/img/plano-alimentar.jpg" alt="Registro de alimentos">
              </div>
              <div class="texto-registro">
                <h2><span class="numero">01</span><br> Registro de alimentos</h2>
                <p>
                  O software permite que os usuários registrem suas refeições diárias, 
                  facilitando o acompanhamento dos alimentos consumidos e suas quantidades.
                </p>
              </div>
            </div>
          </section>


          <section class="secao-sugestoes-planejamento">
            <div class="conteudo-sugestoes">
              <div class="item">
                <div class="imagem-sugestao">
                  <img src="static/img/comida.jpeg" alt="Sugestão de alimentos">
                </div>
                <div class="texto-sugestao">
                  <h2><span class="numero">02</span><br> Sugestão de alimentos</h2>
                  <p>
                    Com base nas preferências e restrições alimentares do usuário, o software pode sugerir receitas e combinações de alimentos saudáveis.
                  </p>
                </div>
              </div>
              <div class="item">
                <div class="texto-planejamento">
                  <h2><span class="numero">03</span><br> Planejamento</h2>
                  <p>
                    Os usuários podem planejar suas refeições, ajudando a economizar tempo e garantir que suas escolhas alimentares sejam saudáveis.
                  </p>
                </div>
                <div class="imagem-planejamento">
                  <img src="static/img/comida.jpeg" alt="Planejamento alimentar">
                </div>
              </div>
            </div>
          </section>


                    
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SmartNutri</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-verde text-white py-4" >
            <a class="navbar-brand" href="{{url_for('index')}}">
                <img src="/static/img/smartnutri.png" alt="logo" height="150">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-label="Alternar navegação" title="Abrir menu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <a href="{{ url_for('auth.cadastro')}}" class="btn btn-danger ms-3 btn-lg">Cadastre-se</a>
                <a href="{{ url_for('auth.login')}}" class="btn btn-danger ms-3 btn-lg" id="entrar">Entrar</a>
        </div>
    </nav>

    
    
    <section class="container text-left py-5 tel-tamanho"">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h1 class="fw-bold">Com SmartNutri você...</h1>
                <h1 class="fw-bold">atende onde estiver.</h1>
                <p>Com o SmartNutri você pode criar planos e acompanhar seus clientes com facilidade.</p>
                <a href="{{ url_for('auth.cadastro')}}" class="btn btn-warning btn-lg w-50 mt-3">Experimente</a>
            </div>
            <div class="col-md-6">
                <img src="/static/img/planoal.png" alt="Coração de frutas" class="img-fluid rounded">
            </div>
        </div>
    </section>

    
    <section class="container text-center py-5 bg-light">
        <h2 class="fw-bold mb-4">Crie Planos Alimentares</h2>
        <div class="d-flex flex-wrap justify-content-center gap-3">
            <button class="btn btn-azul btn-lg" type="button">Prescrição</button>
            <button class="btn btn-rosa btn-lg" type="button">Antropometria</button>
            <button class="btn btn-amarelo btn-lg" type="button">Marketing</button>
        </div>
    </section>


    <section class="container py-5">
        <h2 class="text-center fw-bold">Benefícios</h2>
        <div class="row text-center mt-4">
            <div class="col-md-4">
                <div class="card p-4 shadow">
                    <span class="text-warning fs-3">★★★★☆</span>
                    <h4 class="mt-3">Gestão de tempo</h4>
                    <p>Aproveite as ferramentas disponíveis e não leve mais trabalho para casa!</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card p-4 shadow">
                    <span class="text-warning fs-3">★★★★☆</span>
                    <h4 class="mt-3">Atendimento excelente</h4>
                    <p>Melhore a experiência dos seus clientes com um sistema eficiente.</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card p-4 shadow">
                    <span class="text-warning fs-3">★★★★☆</span>
                    <h4 class="mt-3">Acompanhamento</h4>
                    <p>Monitore a evolução dos seus pacientes com relatórios detalhados.</p>
                </div>
            </div>
        </div>
    </section>


    <footer class="bg-verde text-white text-center py-4">
        <div class="footer">
            <a class="navbar-brand" href="{{url_for('index')}}">
                <img src="/static/img/smartnutri.png" alt="logo" height="100">
            </a>
            <p>O melhor ecossistema de Nutrição do Brasil.</p>
            <div class="d-flex justify-content-center gap-3">
                <img src="/static/img/instagramicon.png " alt="Instagram" height="30">
                <img src="/static/img/facebookicon.png" alt="Facebook" height="30">
                <img src="/static/img/whatsappicon.png"alt="WhatsApp" height="30">
            </div>
            <p class="mt-3">© 2024 SmartNutri | Caicó-RN</p>
            <p><a href="#" class="text-white">Termos de Uso</a> | <a href="#" class="text-white">Política de Privacidade</a></p>
        </div>
    </footer>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>